x_testcase 'nil' ''
x_testcase '{}' ''
x_testcase '{nil}' ''
x_testcase '{{}}' '[{"name":"0"}]'
x_testcase '{{},nil,{}}' '[{"name":"0"},{"name":"0"}]'
x_testcase '{full_text = "Hello, world"}' '[{"name":"0","full_text":"Hello, world"}]'
x_testcase '{{full_text = "Hello, world"}}' '[{"name":"0","full_text":"Hello, world"}]'
x_testcase '{{fpval = 1234.5}}' '[{"name":"0","fpval":1234.5}]'
x_testcase '{{intval = -12345}}' '[{"name":"0","intval":-12345}]'
x_testcase '{{name = "abc"}}' '[{"name":"0"}]'
x_testcase '{{name = 123}}' '[{"name":"0"}]'
x_testcase '{{separator = true}}' '[{"name":"0","separator":true}]'
x_testcase '{{separator = false}}' '[{"name":"0","separator":false}]'
x_testcase '{{foo = true, bar = false}}' '[{"name":"0","foo":true,"bar":false}]'
