#!/usr/bin/env bash

set -e

if (( BASH_VERSINFO[0] < 4 )); then
    echo >&2 "bash 4.0 or higher is required (this one is $BASH_VERSION)."
    exit 1
fi

usage() {
    printf '%s\n' >&2 "$*
USAGE: ${0##*/} [-p lemonbar_argument [-p ...]] -- [luastatus_argument [...]]
Note that '--' is mandatory."
    exit 2
}

lemonbar_args=()
# There is no easy way to require '--' with getopts, so we parse $@ manually.
while true; do
    if (( $# == 0 )); then
        usage "'--' argument not found."
    fi
    case "$1" in
    --)
        shift
        break
        ;;
    -p)
        if (( $# == 1 )); then
            usage "'-p' option requires an argument."
        fi
        shift
        lemonbar_args+=("$1")
        ;;
    -p*)
        lemonbar_args+=("${1:2}")
        ;;
    *)
        usage "Unexpected argument '$1' found before '--'."
        ;;
    esac
    shift
done

coproc ${LEMONBAR:-lemonbar} "${lemonbar_args[@]}"
exec <&${COPROC[0]} >&${COPROC[1]}
exec ${LUASTATUS:-luastatus} -b lemonbar -B in_fd=3 -B out_fd=4 "$@" 3<&0 0</dev/null 4>&1 1>&2
