#!/usr/bin/env bash
if (( BASH_VERSINFO[0] < 4 )); then
    echo >&2 "bash 4.0 or higher is required (this one is $BASH_VERSION)."
    exit 1
fi
coproc ${LEMONBAR:-lemonbar}
eval "exec <&${COPROC[0]} >&${COPROC[1]}"
exec ${LUASTATUS:-luastatus} -b ${LUASTATUS_LEMONBAR_BARLIB:-lemonbar} 3<&0 0</dev/null -B in_fd=3 4>&1 1>&2 -B out_fd=4 "$@"
